"""
config_constants.py — generated by Phase 0, do not edit manually.
All values read from source code + checkpoint inspection.
Model: lerobot/pi0 (Physical Intelligence π0)
"""

# ─── SigLIP Vision Encoder (So400m/patch14-224) ───────────────────────────────
SIGLIP_HIDDEN_SIZE = 1152
SIGLIP_NUM_LAYERS = 27
SIGLIP_NUM_HEADS = 16
SIGLIP_PATCH_SIZE = 14
SIGLIP_IMAGE_SIZE = 224
SIGLIP_INTERMEDIATE_SIZE = 4304
SIGLIP_NUM_IMAGE_TOKENS = (SIGLIP_IMAGE_SIZE // SIGLIP_PATCH_SIZE) ** 2  # 256

# Multi-modal projector: SigLIP hidden → PaliGemma LM hidden
SIGLIP_PROJECTION_DIM = 2048  # == VLM_HIDDEN_SIZE

# ─── PaliGemma LM Backbone (Gemma 2B, prefix stream) ─────────────────────────
VLM_HIDDEN_SIZE = 2048
VLM_NUM_LAYERS = 18
VLM_NUM_HEADS = 8
VLM_NUM_KV_HEADS = 1        # MQA (extreme GQA)
VLM_HEAD_DIM = 256
VLM_INTERMEDIATE_SIZE = 16384
VLM_VOCAB_SIZE = 257152
VLM_RMS_NORM_EPS = 1e-6

# ─── Action Expert (Gemma 300M, suffix stream) ────────────────────────────────
EXPERT_HIDDEN_SIZE = 1024
EXPERT_NUM_LAYERS = 18      # Must match VLM_NUM_LAYERS for per-layer joint attention
EXPERT_NUM_HEADS = 8
EXPERT_NUM_KV_HEADS = 1     # MQA
EXPERT_HEAD_DIM = 256       # == VLM_HEAD_DIM (enables cross-stream KV sharing)
EXPERT_INTERMEDIATE_SIZE = 4096
EXPERT_RMS_NORM_EPS = 1e-6

# ─── Action Head / Flow Matching ─────────────────────────────────────────────
CHUNK_SIZE = 50             # Action tokens per step (action_horizon)
MAX_STATE_DIM = 32
MAX_ACTION_DIM = 32
NUM_INFERENCE_STEPS = 10    # Euler denoising steps
MIN_PERIOD = 4e-3
MAX_PERIOD = 4.0

# ─── Sequence Lengths (for static compilation) ────────────────────────────────
MAX_LANG_TOKENS = 48        # tokenizer_max_length
NUM_IMAGE_TOKENS_PER_CAMERA = SIGLIP_NUM_IMAGE_TOKENS  # 256
NUM_CAMERAS = 3             # lerobot/pi0 checkpoint: 3 cameras (camera0, camera1, camera2)

# Prefix = all image tokens + language tokens
PREFIX_LEN = NUM_IMAGE_TOKENS_PER_CAMERA * NUM_CAMERAS + MAX_LANG_TOKENS  # 816

# Suffix = 1 state token + chunk_size action tokens
SUFFIX_LEN = 1 + CHUNK_SIZE  # 51

# Full attention span for suffix denoiser (attends to prefix KV + itself)
FULL_ATTN_LEN = PREFIX_LEN + SUFFIX_LEN  # 867 (816 prefix + 51 suffix)

# ─── Checkpoint-specific (lerobot/pi0) ────────────────────────────────────────
ACTUAL_STATE_DIM = 6        # real state dim for this checkpoint (padded to MAX_STATE_DIM=32)
ACTUAL_ACTION_DIM = 6       # real action dim (padded to MAX_ACTION_DIM=32)
INPUT_IMAGE_H = 480         # original input resolution (before resize)
INPUT_IMAGE_W = 640
TARGET_IMAGE_H = 224        # after resize_with_pad
TARGET_IMAGE_W = 224

# ─── Misc ─────────────────────────────────────────────────────────────────────
BATCH_SIZE = 1
DTYPE = "bfloat16"

# Sinusoidal time embedding dim (== EXPERT_HIDDEN_SIZE)
TIME_EMBED_DIM = EXPERT_HIDDEN_SIZE  # 1024
