# config_constants.py — generated by Phase 0
# All values verified against checkpoint tensors AND HuggingFace model config.
# Source: lerobot/smolvla_base checkpoint + HuggingFaceTB/SmolVLM2-500M-Video-Instruct
# DO NOT edit manually — update by re-running Phase 0 inspection script.

# ─── VLM TEXT MODEL (SmolLM2, truncated to 16/32 base layers) ────────────────
HIDDEN_SIZE = 960                  # text_model embed_tokens [49280, 960]
NUM_ATTENTION_HEADS = 15           # q_proj [960, 960] → 15 * 64 = 960
NUM_KEY_VALUE_HEADS = 5            # k_proj [320, 960] → 5 * 64 = 320
HEAD_DIM = 64
INTERMEDIATE_SIZE = 2560           # mlp.down_proj [960, 2560]
NUM_HIDDEN_LAYERS = 16             # layers 0-15 in checkpoint
VOCAB_SIZE = 49280
ROPE_THETA = 100_000               # from SmolLM2-500M base config
RMS_NORM_EPS = 1e-5
VLM_KV_DIM = 320                   # = NUM_KEY_VALUE_HEADS * HEAD_DIM

# ─── VISION ENCODER (SigLIP ViT) ─────────────────────────────────────────────
VISION_HIDDEN_SIZE = 768           # vision_model patch_embedding bias [768]
VISION_NUM_HEADS = 12              # self_attn q_proj [768, 768] → 12 * 64 = 768
VISION_HEAD_DIM = 64
VISION_INTERMEDIATE_SIZE = 3072    # mlp.fc1.weight [3072, 768]
VISION_NUM_LAYERS = 12             # encoder layers 0-11
VISION_PATCH_SIZE = 16             # patch_embedding.weight [768, 3, 16, 16]
VISION_IMAGE_SIZE = 512            # resize_imgs_with_padding in SmolVLAConfig
VISION_NUM_PATCHES_PER_DIM = 32    # = VISION_IMAGE_SIZE / VISION_PATCH_SIZE
VISION_NUM_PATCHES = 1024          # = 32 * 32; position_embedding [1024, 768]
VISION_PIXEL_SHUFFLE_SCALE = 4     # PixelShuffle 4×4 → 16:1 reduction
VISION_TOKENS_PER_CAMERA = 64      # = 1024 / 16 (after pixel shuffle)
# Connector: pixel-shuffle flattens 4×4 patches → 12288-dim, then projects to 960
VISION_CONNECTOR_INPUT_DIM = 12288  # = VISION_HIDDEN_SIZE * VISION_PIXEL_SHUFFLE_SCALE**2
VISION_CONNECTOR_OUTPUT_DIM = 960   # = HIDDEN_SIZE; connector.proj.weight [960, 12288]

# ─── ACTION EXPERT (smaller SmolLM2 variant, interleaved self/cross-attn) ────
EXPERT_HIDDEN_SIZE = 720           # 0.75 * HIDDEN_SIZE; lm_expert layer norms [720]
EXPERT_NUM_HEADS = 15              # q_proj [960, 720] → 15 * 64 = 960 (Q proj to VLM Q dim)
EXPERT_NUM_KV_HEADS = 5
EXPERT_HEAD_DIM = 64
EXPERT_INTERMEDIATE_SIZE = 2048    # mlp.down_proj [720, 2048]
EXPERT_NUM_LAYERS = 16             # same depth as VLM
EXPERT_SELF_ATTN_EVERY_N_LAYERS = 2  # even layers = self-attn, odd = cross-attn
EXPERT_NUM_CROSS_ATTN_LAYERS = 8   # layers 1, 3, 5, 7, 9, 11, 13, 15
# Cross-attn k/v proj maps VLM KV (320) → expert KV (320)
EXPERT_CROSS_ATTN_KV_IN = VLM_KV_DIM   # = 320
EXPERT_CROSS_ATTN_KV_OUT = 320          # = EXPERT_NUM_KV_HEADS * EXPERT_HEAD_DIM

# ─── ACTION & TIMESTEP ───────────────────────────────────────────────────────
ACTION_CHUNK_SIZE = 50             # config.chunk_size
ACTION_DIM = 32                    # config.max_action_dim; action_in_proj [720, 32]
STATE_DIM = 32                     # config.max_state_dim; state_proj [960, 32]
NUM_DENOISING_STEPS = 10           # config.num_steps
MIN_PERIOD = 0.004                 # sinusoidal embedding min_period
MAX_PERIOD = 4.0                   # sinusoidal embedding max_period
# Sinusoidal encoding produces EXPERT_HIDDEN_SIZE features (360 sin + 360 cos).
# action_time_mlp_in: Linear(EXPERT_HIDDEN_SIZE * 2, EXPERT_HIDDEN_SIZE) [720, 1440]
# action_time_mlp_out: Linear(EXPERT_HIDDEN_SIZE, EXPERT_HIDDEN_SIZE)    [720, 720]
TIMESTEP_SINUSOIDAL_DIM = EXPERT_HIDDEN_SIZE  # = 720 (sin + cos → 720)
TIMESTEP_MLP_INPUT_DIM = EXPERT_HIDDEN_SIZE * 2  # = 1440 (action_emb cat time_emb)
TIMESTEP_EMBED_DIM = EXPERT_HIDDEN_SIZE       # = 720 (output of action_time_mlp_out)

# ─── SEQUENCE LENGTHS (for 1-camera inference, the default) ──────────────────
TOKENIZER_MAX_LENGTH = 48          # config.tokenizer_max_length
NUM_TEXT_TOKENS = TOKENIZER_MAX_LENGTH          # = 48
NUM_VISION_TOKENS = VISION_TOKENS_PER_CAMERA    # = 64 (per camera)
NUM_STATE_TOKENS = 1               # state_proj produces a single token
NUM_CAMERAS = 1                    # default; scales NUM_VISION_TOKENS linearly
PREFIX_SEQ_LEN = NUM_TEXT_TOKENS + NUM_VISION_TOKENS * NUM_CAMERAS + NUM_STATE_TOKENS
# = 48 + 64 + 1 = 113

# ─── CONDITIONING CONTRACT (VLM → Action Expert interface) ───────────────────
# The VLM prefix pass fills a per-layer KV cache for all 16 VLM layers.
# For cross-attn expert layers, K and V come from the VLM KV at that same layer.
# We package the 8 cross-attn layers' K+V as a single conditioning tensor:
#   [B, PREFIX_SEQ_LEN, EXPERT_NUM_CROSS_ATTN_LAYERS * 2 * VLM_KV_DIM]
#   = [B, 113, 8 * 2 * 320] = [B, 113, 5120]
NUM_CONDITIONING_TOKENS = PREFIX_SEQ_LEN        # = 113
CONDITIONING_HIDDEN_SIZE = EXPERT_NUM_CROSS_ATTN_LAYERS * 2 * VLM_KV_DIM  # = 5120

# ─── HARDWARE TARGET ─────────────────────────────────────────────────────────
BATCH_SIZE = 1
TP_DEGREE_VISION = 1               # vision encoder: ~86M params, tp=1 sufficient
TP_DEGREE_VLM = 8                  # VLM backbone: ~500M params, tp=8
TP_DEGREE_EXPERT = 2               # expert: ~100M params, tp=2 (verify at compile time)

# ─── COMPILER FLAGS (per subgraph) ───────────────────────────────────────────
VISION_FLAGS  = '--enable-saturate-infinity --model-type transformer'
VLM_FLAGS     = '--enable-saturate-infinity --model-type transformer --enable-mixed-precision-accumulation'
EXPERT_FLAGS  = '--enable-saturate-infinity --model-type transformer --enable-mixed-precision-accumulation'
