# config_constants.py — generated by Phase 0, verified against checkpoint tensors
# nvidia/GR00T-N1.7-3B checkpoint:
# /home/ubuntu/.cache/huggingface/hub/models--nvidia--GR00T-N1.7-3B/snapshots/2fc962b973bccdd5d8ce4f67cc63b264d6886495
# All values cross-checked against safetensors weight shapes.
# DO NOT edit manually. Re-derive from the checkpoint if shapes change.

import os

MODEL_PATH = os.environ.get(
    "GROOT_MODEL_PATH",
    "/home/ubuntu/.cache/huggingface/hub/models--nvidia--GR00T-N1.7-3B/snapshots/"
    "2fc962b973bccdd5d8ce4f67cc63b264d6886495",
)

# ---------------------------------------------------------------------------
# Batch / hardware
# ---------------------------------------------------------------------------
BATCH_SIZE = 1
TP_DEGREE_VLM    = 8   # Backbone + VL self-attn: NxDI TP=8 (trn1.32xlarge, 32 NeuronCores)
TP_DEGREE_VISION = 1   # Vision encoder: torch_neuronx.trace(), single-device
TP_DEGREE_DIT    = 8   # DiT action head: NeuronDenoisingWrapper via ModelBuilder

# ---------------------------------------------------------------------------
# Vision encoder (Qwen3-VL ViT, backbone.model.model.visual.*)
# Verified: backbone.model.model.visual.blocks.0.attn.qkv.weight = (3072, 1024)
# ---------------------------------------------------------------------------
VIT_NUM_LAYERS          = 24    # blocks 0-23
VIT_HIDDEN_SIZE         = 1024  # confirmed: qkv.weight (3072, 1024) → out_dim=1024
VIT_NUM_HEADS           = 16    # 3072/3/64 = 16 heads, head_dim=64
VIT_HEAD_DIM            = 64
VIT_INTERMEDIATE_SIZE   = 4096  # mlp.linear_fc1.weight (4096, 1024)
VIT_PATCH_SIZE          = 16    # patch_embed.proj.weight (1024, 3, 2, 16, 16)
VIT_TEMPORAL_PATCH_SIZE = 2     # patch_embed temporal dim = 2
VIT_SPATIAL_MERGE_SIZE  = 2     # 2×2 spatial merge after ViT
VIT_POS_EMBED_SIZE      = 2304  # pos_embed.weight (2304, 1024) = max vision positions
VIT_DEEPSTACK_MERGERS   = 3     # deepstack_merger_list: 3 intermediate layers (5, 11, 17)
VIT_OUTPUT_DIM          = 2048  # merger.linear_fc2.weight (2048, 4096) → projected to 2048

# Image preprocessing (from config.json)
IMAGE_TARGET_SIZE = (256, 256)  # input image resized to this before ViT
IMAGE_CROP_SIZE   = (230, 230)  # crop before resize

# Vision tokens per image (after spatial merge 2×2):
# For 256×256 with patch_size=16: 16×16 patches / (2×2 merge) = 64 tokens
# 2 video frames processed as 1 temporal unit (temporal_patch_size=2)
VISION_TOKENS_PER_IMAGE = 64    # image_grid_thw = [1, 16, 16] → 64 after merge

# ---------------------------------------------------------------------------
# VLM backbone (Qwen3-VL-2B LLM, backbone.model.model.language_model.*)
# Only select_layer=16 layers are used (layers 0-15 in checkpoint)
# Verified: q_proj (2048,2048), k_proj (1024,2048), gate_proj (6144,2048)
# ---------------------------------------------------------------------------
LLM_HIDDEN_SIZE         = 2048   # embed_tokens.weight (151936, 2048)
LLM_NUM_LAYERS          = 16     # layers 0-15 (select_layer=16; layers 16-27 dropped)
LLM_TOTAL_LAYERS        = 28     # original Qwen3-VL-2B has 28 layers
LLM_NUM_ATTENTION_HEADS = 16     # q_proj (2048, 2048) / head_dim(128) = 16
LLM_NUM_KV_HEADS        = 8      # k_proj (1024, 2048) / head_dim(128) = 8
LLM_HEAD_DIM            = 128    # q_norm.weight (128,)
LLM_INTERMEDIATE_SIZE   = 6144   # gate_proj.weight (6144, 2048)
LLM_VOCAB_SIZE          = 151936 # embed_tokens.weight (151936, 2048)
LLM_ROPE_THETA          = 5e6    # from Qwen3-VL-2B config

# Sequence length — MUST be pinned for Neuron compilation.
# Derived: 2 images × 64 vision tokens + ~128 text/template tokens, padded to 256.
# VERIFY via actual forward pass before compilation. Adjust if real seq_len differs.
NUM_VISION_TOKENS   = 128   # 2 video frames × 64 tokens (temporal_patch_size=2 groups them)
NUM_TEXT_TOKENS     = 128   # max text tokens (instruction + template), padded
NUM_CONDITIONING_TOKENS = NUM_VISION_TOKENS + NUM_TEXT_TOKENS  # = 256
CONDITIONING_HIDDEN_SIZE = LLM_HIDDEN_SIZE  # = 2048; backbone output dim fed to DiT

# ---------------------------------------------------------------------------
# VL self-attention (SelfAttentionTransformer, action_head.vl_self_attention.*)
# Verified: to_q.weight (2048, 2048), ff.net.0.proj.weight (8192, 2048)
# ---------------------------------------------------------------------------
VL_SELF_ATTN_NUM_LAYERS         = 4     # transformer_blocks 0-3
VL_SELF_ATTN_HIDDEN_SIZE        = 2048  # to_q.weight (2048, 2048)
VL_SELF_ATTN_NUM_HEADS          = 32    # from config vl_self_attention_cfg
VL_SELF_ATTN_HEAD_DIM           = 64    # 2048 / 32 = 64
VL_SELF_ATTN_INTERMEDIATE_SIZE  = 8192  # ff.net.0.proj (8192, 2048)
# Output dim: same as input (2048) — no projection layer in SelfAttentionTransformer

# ---------------------------------------------------------------------------
# DiT action head (AlternateVLDiT, action_head.model.*)
# Verified: to_q.weight (1536, 1536), to_k.weight (1536, 2048) for cross-attn blocks
# ---------------------------------------------------------------------------
DIT_NUM_LAYERS          = 32    # transformer_blocks 0-31
DIT_HIDDEN_SIZE         = 1536  # = 32 heads × 48 head_dim; to_q.weight (1536, 1536)
DIT_NUM_HEADS           = 32    # from config diffusion_model_cfg
DIT_HEAD_DIM            = 48    # from config
DIT_INTERMEDIATE_SIZE   = 6144  # ff.net.0.proj.weight (6144, 1536)
DIT_OUTPUT_DIM          = 1024  # proj_out_2.weight (1024, 1536) = hidden_size
DIT_CROSS_ATTN_DIM      = 2048  # K/V come from conditioning: to_k.weight (1536, 2048)
DIT_ATTEND_TEXT_EVERY_N = 2     # attend_text_every_n_blocks from config

# Attention pattern: block i is self-attention if i%2==1, cross-attention if i%2==0
# Cross-attention alternates between non-image and image tokens:
#   block i (cross-attn): non-image if i%(2*attend_text_every_n)==0, else image
#   attend_text_every_n=2 → non-image at blocks 0,8,16,24; image at blocks 4,12,20,28

# ---------------------------------------------------------------------------
# Timestep encoder (action_head.model.timestep_encoder.*)
# Verified: linear_1.weight (1536, 256), linear_2.weight (1536, 1536)
# ---------------------------------------------------------------------------
TIMESTEP_SINUSOIDAL_DIM = 256   # Timesteps sinusoidal channels
TIMESTEP_EMBED_DIM      = 1536  # projected embedding dim (= DIT_HIDDEN_SIZE)
                                 # Pass this as timestep_embedding to compiled DiT

# ---------------------------------------------------------------------------
# Action head inputs/outputs
# Verified: action_encoder.W1.W (32, 132, 1536), action_decoder.layer2.W (32, 1024, 132)
# ---------------------------------------------------------------------------
ACTION_HORIZON          = 40    # action_horizon from config
MAX_ACTION_DIM          = 132   # max_action_dim from config
MAX_STATE_DIM           = 132   # max_state_dim from config
STATE_HISTORY_LENGTH    = 1     # state_history_length from config
MAX_NUM_EMBODIMENTS     = 32    # action_encoder.W1.W (32, ...) = 32 embodiments
INPUT_EMBEDDING_DIM     = 1536  # input_embedding_dim from config = DIT_HIDDEN_SIZE
ACTION_OUTPUT_DIM       = DIT_OUTPUT_DIM  # = 1024; action_decoder maps 1024→action_dim

# DiT input sequence (state tokens + action tokens, encoded on CPU):
# sa_embs = cat(state_features[B,1,1536], action_features[B,40,1536]) → [B,41,1536]
DIT_INPUT_SEQ_LEN = STATE_HISTORY_LENGTH + ACTION_HORIZON  # = 41

# ---------------------------------------------------------------------------
# Flow matching / denoising
# ---------------------------------------------------------------------------
NUM_INFERENCE_TIMESTEPS = 4     # num_inference_timesteps from config
NUM_TIMESTEP_BUCKETS    = 1000  # num_timestep_buckets from config

# ---------------------------------------------------------------------------
# Compiler flags
# ---------------------------------------------------------------------------
VISION_FLAGS = (
    "--auto-cast=none "
    "--model-type=transformer "
    "--tensorizer-options='"
    "--enable-ccop-compute-overlap "
    "--cc-pipeline-tiling-factor=1'"
)

VLM_FLAGS = (
    "--auto-cast=none "
    "--model-type=transformer "
    "--tensorizer-options='"
    "--enable-ccop-compute-overlap "
    "--cc-pipeline-tiling-factor=1'"
)

DIT_FLAGS = (
    "--auto-cast=none "
    "--model-type=transformer "
    "--tensorizer-options='"
    "--enable-ccop-compute-overlap "
    "--cc-pipeline-tiling-factor=1'"
)
